[font]
size = 16.0

[font.normal]
family = "CodeNewRoman Nerd Font"
style = "Regular"

[colors.primary]
foreground = "#ebdbb2"
background = "#282828"

[window]
opacity = 0.9
dynamic_padding = true
padding = { x = 10, y = 3 }

[bell]
command = "None"
animation = "EaseOutExpo"
duration = 0

