general {
		color_good = "#00FF00"
		color_bad = "#ff0c00"
        colors = true
		interval = 2
}

order += "disk /"
order += "cpu_temperature 0"
order += "battery all"
order += "volume master"
order += "time"

disk "/" {
	 	format = "Used: %percentage_used"
		separator_block_width = 20
}

cpu_temperature 0 {
        format = "CPU: %degrees°C"
		max_threshold = 60
		separator_block_width = 20
}

battery all {
		status_bat = "BAT"
		status_chr = "CHARGING"
		status_full = "FULL"
		format_percentage = "%.00f%s"
		format = "%status %percentage"
		low_threshold = 30
		separator_block_width = 20
}

volume master {
	   	format = "Volume: %volume"
	   	format_muted = "Muted"
		separator_block_width = 20
}

time {
		format = "%H:%M %p"
}
